import type { GameBuildSpec, RuntimeStats } from "@/app/types/game";

function safeJson(value: unknown) {
  return JSON.stringify(value).replace(/</g, "\\u003c");
}

export function downloadTextFile(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function downloadBuildSpec(spec: GameBuildSpec) {
  downloadTextFile(`${slug(spec.title)}-gameforge-build.json`, JSON.stringify(spec, null, 2), "application/json");
}

export function downloadPlaytestReport(spec: GameBuildSpec, stats: RuntimeStats) {
  const report = {
    game: spec.title,
    buildId: spec.buildId,
    schemaVersion: spec.schemaVersion,
    dimension: spec.renderer.dimension,
    renderer: stats.renderer || "Native WebGL 2",
    averageFps: stats.fps || null,
    template: spec.template,
    objective: spec.objective,
    result: stats.status,
    elapsedSeconds: Number(stats.elapsed.toFixed(2)),
    score: stats.score,
    healthRemaining: stats.health,
    defeated: stats.defeated,
    collected: stats.collected,
    progress: `${stats.progress}/${stats.target}`,
    testedAt: new Date().toISOString(),
  };
  downloadTextFile(`${slug(spec.title)}-playtest-report.json`, JSON.stringify(report, null, 2), "application/json");
}

export function downloadStandaloneGame(spec: GameBuildSpec) {
  downloadTextFile(`${slug(spec.title)}-webgl-3d.html`, buildStandaloneHtml(spec), "text/html");
}

function slug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60) || "gameforge-game";
}

export function buildStandaloneHtml(spec: GameBuildSpec) {
  if (spec.template === "flight") return buildFlightStandaloneHtml(spec);
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" />
<title>${escapeHtml(spec.title)} — Gameforge Native 3D</title>
<style>
*{box-sizing:border-box}html,body{margin:0;height:100%;overflow:hidden;background:#020308;color:#fff;font-family:Inter,system-ui,Arial,sans-serif}canvas{display:block;width:100%;height:100%;outline:none;cursor:crosshair;touch-action:none}.hud{position:fixed;inset:0;pointer-events:none}.top{display:flex;justify-content:space-between;gap:14px;padding:16px}.panel{background:rgba(3,4,12,.7);border:1px solid rgba(255,255,255,.13);backdrop-filter:blur(16px);border-radius:16px;padding:12px 14px;box-shadow:0 14px 50px rgba(0,0,0,.38)}h1{font-size:16px;margin:0}.small{font-size:11px;color:#b8bbc5;margin-top:5px;max-width:440px}.bar{width:200px;height:7px;background:#27272a;border-radius:99px;overflow:hidden;margin-top:9px}.bar>i{display:block;height:100%;background:linear-gradient(90deg,${spec.visual.enemy},${spec.visual.secondaryAccent});transition:width .15s}.center{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);text-align:center;background:rgba(3,3,10,.82);border:1px solid rgba(255,255,255,.14);padding:30px 36px;border-radius:26px;pointer-events:auto;cursor:pointer;box-shadow:0 30px 100px rgba(0,0,0,.6)}.center.hidden{display:none}.center strong{font-size:clamp(25px,4vw,38px);display:block}.center span{font-size:13px;color:#d4d4d8;display:block;margin-top:10px;line-height:1.6}.help{position:absolute;left:16px;bottom:16px;font-size:11px;color:#d4d4d8}.stats{font-weight:900;color:${spec.visual.collectible};text-align:right}.cross{position:absolute;left:50%;top:50%;width:12px;height:12px;transform:translate(-50%,-50%);border:1px solid rgba(255,255,255,.55);border-radius:50%}.message{position:absolute;left:50%;top:72%;transform:translateX(-50%);max-width:min(720px,85vw);text-align:center;font-weight:800;color:#fff;text-shadow:0 2px 12px #000}.error{display:none;position:fixed;inset:0;z-index:10;place-items:center;background:#05030c;padding:30px;text-align:center}.error.show{display:grid}.error div{max-width:620px;border:1px solid rgba(248,113,113,.3);background:rgba(127,29,29,.22);padding:28px;border-radius:24px}.mobile{display:none;position:absolute;inset:auto 14px 14px;justify-content:space-between;pointer-events:auto}.pad,.actions{display:grid;gap:7px}.pad{grid-template-columns:repeat(3,46px)}.actions{grid-template-columns:repeat(2,54px);align-content:end}.touch{height:46px;border:1px solid rgba(255,255,255,.16);border-radius:14px;background:rgba(0,0,0,.55);color:#fff;font-weight:900}.blank{visibility:hidden}@media(pointer:coarse){.mobile{display:flex}.help{display:none}.cross{display:none}}
</style>
</head>
<body>
<canvas id="game" tabindex="0" aria-label="${escapeHtml(spec.title)} native WebGL 3D game"></canvas>
<div class="hud">
  <div class="top">
    <div class="panel"><h1>${escapeHtml(spec.title)}</h1><div class="small">${escapeHtml(spec.objective.description)}</div></div>
    <div class="panel"><div class="stats" id="score">Score 0</div><div class="small" id="progress">Progress 0/${spec.objective.target} · 0 FPS</div><div class="bar"><i id="health" style="width:100%"></i></div></div>
  </div>
  <div class="cross"></div>
  <div class="message" id="message">${escapeHtml(spec.narrative.openingLine)}</div>
  <div class="center" id="start"><strong>Launch Native 3D</strong><span>WASD move · Space attack/jump · Shift dash · E interact · Mouse orbit · R restart</span></div>
  <div class="help panel">Native WebGL 2 · ${escapeHtml(spec.tagline)}</div>
  <div class="mobile"><div class="pad"><button class="touch blank"></button><button class="touch" data-key="w">▲</button><button class="touch blank"></button><button class="touch" data-key="a">◀</button><button class="touch" data-key="s">▼</button><button class="touch" data-key="d">▶</button></div><div class="actions"><button class="touch" data-key="e">USE</button><button class="touch" data-key=" ">ACT</button></div></div>
</div>
<div class="error" id="error"><div><h2>WebGL 2 is required</h2><p>Enable hardware acceleration or open this build in a current Chrome, Edge, Firefox, or Safari browser.</p></div></div>
<script>
(function(){'use strict';
var SPEC=${safeJson(spec)};
var canvas=document.getElementById('game'),gl=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});
if(!gl){document.getElementById('error').classList.add('show');return;}
var keys=new Set(),run=false,last=0,elapsed=0,score=0,progress=0,defeated=0,collected=0,status='ready',yaw=0,pitch=-.28,zoom=16,targetLane=0,grounded=true,lastAttack=-10,drag=false,dragX=0,dragY=0,fps=60,frames=0,fpsClock=0;
var player,enemies=[],items=[],shots=[],obstacles=[],platforms=[],nodes=[],particles=[];
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function rgb(h){h=h.replace('#','');return[parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255]}
function seed(t){var s=2166136261;for(var i=0;i<t.length;i++)s=Math.imul(s^t.charCodeAt(i),16777619);return function(){s+=0x6d2b79f5;var v=s;v=Math.imul(v^v>>>15,v|1);v^=v+Math.imul(v^v>>>7,v|61);return((v^v>>>14)>>>0)/4294967296}}var random=seed(SPEC.buildId+SPEC.title);
function ident(){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1])}function mul(a,b){var o=new Float32Array(16);for(var r=0;r<4;r++)for(var c=0;c<4;c++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}function trans(x,y,z){var o=ident();o[12]=x;o[13]=y;o[14]=z;return o}function scale(x,y,z){var o=ident();o[0]=x;o[5]=y;o[10]=z;return o}function rotY(a){var c=Math.cos(a),s=Math.sin(a);return new Float32Array([c,0,-s,0,0,1,0,0,s,0,c,0,0,0,0,1])}function model(x,y,z,sx,sy,sz,a){return mul(trans(x,y,z),mul(rotY(a||0),scale(sx,sy,sz)))}function persp(fov,aspect,n,f){var q=1/Math.tan(fov/2),nf=1/(n-f);return new Float32Array([q/aspect,0,0,0,0,q,0,0,0,0,(f+n)*nf,-1,0,0,2*f*n*nf,0])}function norm(v){var l=Math.hypot(v[0],v[1],v[2])||1;return[v[0]/l,v[1]/l,v[2]/l]}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}function look(eye,t){var z=norm([eye[0]-t[0],eye[1]-t[1],eye[2]-t[2]]),x=norm(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-(x[0]*eye[0]+x[1]*eye[1]+x[2]*eye[2]),-(y[0]*eye[0]+y[1]*eye[1]+y[2]*eye[2]),-(z[0]*eye[0]+z[1]*eye[1]+z[2]*eye[2]),1])}
function shader(type,source){var s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}var vs=shader(gl.VERTEX_SHADER,'#version 300 es\\nprecision highp float;layout(location=0)in vec3 p;layout(location=1)in vec3 n;uniform mat4 P,V,M;out vec3 w,N;void main(){vec4 q=M*vec4(p,1.);w=q.xyz;N=normalize(mat3(M)*n);gl_Position=P*V*q;}');var fs=shader(gl.FRAGMENT_SHADER,'#version 300 es\\nprecision highp float;in vec3 w,N;uniform vec3 C,L,E,F;uniform float X,FN,FF,T;out vec4 o;void main(){vec3 n=normalize(N);float d=max(dot(n,normalize(-L)),0.);float h=n.y*.5+.5;vec3 v=normalize(E-w);float r=pow(1.-max(dot(n,v),0.),2.4);vec3 c=C*(.22+d*.7+h*.18)+C*X*(.8+r*.8)+vec3(r*.1);float fog=smoothstep(FN,FF,distance(w,E));o=vec4(mix(c,F,fog),1.);}');var program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program));gl.useProgram(program);
var U={P:gl.getUniformLocation(program,'P'),V:gl.getUniformLocation(program,'V'),M:gl.getUniformLocation(program,'M'),C:gl.getUniformLocation(program,'C'),L:gl.getUniformLocation(program,'L'),E:gl.getUniformLocation(program,'E'),F:gl.getUniformLocation(program,'F'),X:gl.getUniformLocation(program,'X'),FN:gl.getUniformLocation(program,'FN'),FF:gl.getUniformLocation(program,'FF'),T:gl.getUniformLocation(program,'T')};
var pos=[-1,-1,1,1,-1,1,1,1,1,-1,1,1,1,-1,-1,-1,-1,-1,-1,1,-1,1,1,-1,-1,1,1,1,1,1,1,1,-1,-1,1,-1,-1,-1,-1,1,-1,1,-1,1,-1,-1,1,-1,1,-1,1,1,-1,1,1,1,-1,-1,-1,-1,-1,1,-1,1,1,-1,1,-1];var nor=[0,0,1,0,0,1,0,0,1,0,0,1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,1,0,0,1,0,0,1,0,0,1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0,1,0,0,1,0,0,1,0,0,1,0,0,-1,0,0,-1,0,0,-1,0,0,-1,0];var ind=[];for(var f=0;f<6;f++){var q=f*4;ind.push(q,q+1,q+2,q,q+2,q+3)}var vao=gl.createVertexArray();gl.bindVertexArray(vao);var pb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,pb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(pos),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);var nb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,nb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(nor),gl.STATIC_DRAW);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,0,0);var ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(ind),gl.STATIC_DRAW);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);
function cube(x,y,z,sx,sy,sz,color,em,a){var c=rgb(color);gl.uniformMatrix4fv(U.M,false,model(x,y,z,sx,sy,sz,a));gl.uniform3f(U.C,c[0],c[1],c[2]);gl.uniform1f(U.X,em||0);gl.bindVertexArray(vao);gl.drawElements(gl.TRIANGLES,ind.length,gl.UNSIGNED_SHORT,0)}
function entity(id,x,y,z,r,h){return{id:id,x:x,y:y,z:z,vx:0,vy:0,vz:0,r:r,h:h,max:h,c:0,a:0,dead:false,active:false}}
function safe(half){var x,z;do{x=(random()*2-1)*half*.82;z=(random()*2-1)*half*.82}while(Math.hypot(x,z)<7);return[x,z]}
function reset(){var half=SPEC.world.size/2;player=entity(0,SPEC.template==='platformer'?-half+6:0,1.4,0,.75,SPEC.player.health);enemies=[];items=[];shots=[];obstacles=[];platforms=[];nodes=[];particles=[];elapsed=score=progress=defeated=collected=0;targetLane=0;grounded=true;lastAttack=-10;yaw=0;pitch=-.28;zoom=SPEC.template==='platformer'?22:16;
if(SPEC.template!=='runner'&&SPEC.template!=='platformer'){for(var i=0;i<SPEC.enemy.count;i++){var e=safe(half);enemies.push(entity(i+1,e[0],1.1,e[1],.75,SPEC.enemy.health))}var count=SPEC.template==='collector'?SPEC.objective.target:Math.max(6,Math.min(16,SPEC.collectible.count));for(i=0;i<count;i++){var it=safe(half),item=entity(i+1,it[0],1.2+random(),it[1],.42,1);item.value=SPEC.collectible.scoreValue;items.push(item)}for(i=0;i<SPEC.world.obstacleCount;i++){var o=safe(half),t=random()<.32;obstacles.push({x:o[0],y:t?1.8:.65,z:o[1],sx:.7+random()*1.7,sy:t?1.8+random()*2.5:.55+random()*.6,sz:.7+random()*1.7,hit:false})}}
if(SPEC.template==='runner'){player.x=0;player.y=1;for(i=0;i<SPEC.world.obstacleCount;i++){var lane=i%3-1;obstacles.push({x:lane*4,y:1,z:12+i*(SPEC.world.size/SPEC.world.obstacleCount)+random()*5,sx:1.2,sy:1+random()*1.5,sz:1,hit:false})}for(i=0;i<Math.max(18,SPEC.collectible.count);i++){lane=i%3-1;item=entity(i,lane*4,1.3,8+i*5.5,.4,1);item.value=SPEC.collectible.scoreValue;items.push(item)}}
if(SPEC.template==='platformer'){var x=-half+4;platforms.push({x:x,y:0,w:12,h:1});for(i=0;i<SPEC.world.platformCount;i++){var w=3+random()*4;x+=w+1.5+random()*2;var py=random()*Math.min(6,SPEC.world.verticality);platforms.push({x:x,y:py,w:w,h:.7});if(i%2===0){item=entity(i,x,py+1.4,0,.38,1);item.value=SPEC.collectible.scoreValue;items.push(item)}}platforms.push({x:x+10,y:1,w:10,h:1});player.x=-half+4;player.y=1.6}
if(SPEC.template==='puzzle'){for(i=0;i<SPEC.objective.target;i++){var a=i/SPEC.objective.target*Math.PI*2,n=entity(i+1,Math.cos(a)*half*.55,1.2,Math.sin(a)*half*.55,.8,1);n.order=i+1;nodes.push(n)}}status='playing';run=true;last=performance.now();document.getElementById('start').classList.add('hidden');document.getElementById('message').textContent=SPEC.narrative.openingLine;canvas.focus()}
function burst(x,y,z,c,n){for(var i=0;i<n;i++){var a=Math.random()*Math.PI*2,v=2+Math.random()*5;particles.push({x:x,y:y,z:z,vx:Math.cos(a)*v,vy:1+Math.random()*v,vz:Math.sin(a)*v,l:.4+Math.random()*.7,c:c})}}
function attack(now){if(now-lastAttack<SPEC.player.attackCooldown)return;lastAttack=now;var dx=Math.sin(player.a||yaw),dz=Math.cos(player.a||yaw);shots.push({x:player.x+dx,y:1.25,z:player.z+dz,vx:dx*22,vz:dz*22,l:1.4,r:.2});burst(player.x,1.2,player.z,SPEC.visual.projectile,7)}
function update(dt,now){elapsed+=dt;var half=SPEC.world.size/2;
if(SPEC.template==='runner'){if(keys.has('a')||keys.has('arrowleft')){targetLane=Math.max(-1,targetLane-1);keys.delete('a');keys.delete('arrowleft')}if(keys.has('d')||keys.has('arrowright')){targetLane=Math.min(1,targetLane+1);keys.delete('d');keys.delete('arrowright')}player.x+=(targetLane*4-player.x)*Math.min(1,dt*10);player.z+=SPEC.player.speed*1.45*dt;if((keys.has(' ')||keys.has('w'))&&grounded){player.vy=SPEC.player.jumpForce*.7;grounded=false;keys.delete(' ')}player.vy-=24*dt;player.y+=player.vy*dt;if(player.y<=1){player.y=1;player.vy=0;grounded=true}for(var i=0;i<obstacles.length;i++){var o=obstacles[i];if(!o.hit&&Math.abs(o.z-player.z)<o.sz+1&&Math.abs(o.x-player.x)<o.sx+.7&&player.y<o.y+o.sy+.2){o.hit=true;player.h-=SPEC.enemy.damage*1.4;burst(player.x,player.y,player.z,SPEC.visual.enemy,18)}}progress=Math.min(SPEC.objective.target,Math.floor(player.z*8))}
else if(SPEC.template==='platformer'){var input=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);player.vx=input*SPEC.player.speed*.9;player.x+=player.vx*dt;if((keys.has(' ')||keys.has('w'))&&grounded){player.vy=SPEC.player.jumpForce;grounded=false;keys.delete(' ')}player.vy-=26*dt;var old=player.y;player.y+=player.vy*dt;grounded=false;for(i=0;i<platforms.length;i++){var p=platforms[i],top=p.y+p.h;if(player.x>p.x-p.w/2-player.r&&player.x<p.x+p.w/2+player.r&&old-player.r>=top-.2&&player.y-player.r<=top&&player.vy<=0){player.y=top+player.r;player.vy=0;grounded=true}}if(player.y<-8){player.h-=25;player.x=Math.max(-half+4,player.x-7);player.y=8;player.vy=0}var final=platforms[platforms.length-1];progress=player.x>final.x?1:0}
else{var ix=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),iz=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0),len=Math.hypot(ix,iz)||1;ix/=len;iz/=len;var sp=SPEC.player.speed*(keys.has('shift')?SPEC.player.dashMultiplier:1),sn=Math.sin(yaw),cs=Math.cos(yaw),wx=ix*cs-iz*sn,wz=ix*sn+iz*cs;player.x=clamp(player.x+wx*sp*dt,-half+1,half-1);player.z=clamp(player.z+wz*sp*dt,-half+1,half-1);if(Math.abs(wx)+Math.abs(wz)>.1)player.a=Math.atan2(wx,wz);if(keys.has(' ')||keys.has('attack')){attack(now);keys.delete('attack')}
for(i=0;i<shots.length;i++){var sh=shots[i];sh.x+=sh.vx*dt;sh.z+=sh.vz*dt;sh.l-=dt;for(var j=0;j<enemies.length;j++){var en=enemies[j];if(en.dead||sh.dead)continue;if(Math.hypot(sh.x-en.x,sh.z-en.z)<en.r+sh.r){sh.dead=true;en.h-=SPEC.player.attackPower;burst(sh.x,1.2,sh.z,SPEC.visual.projectile,9);if(en.h<=0){en.dead=true;defeated++;score+=250;burst(en.x,en.y,en.z,SPEC.visual.enemy,20)}}}}shots=shots.filter(function(s){return !s.dead&&s.l>0});for(i=0;i<enemies.length;i++){en=enemies[i];if(en.dead)continue;var dx=player.x-en.x,dz=player.z-en.z,dist=Math.hypot(dx,dz)||1;en.a=Math.atan2(dx,dz);if(dist<18||SPEC.enemy.behavior==='swarm'){en.x+=dx/dist*SPEC.enemy.speed*dt;en.z+=dz/dist*SPEC.enemy.speed*dt}en.c-=dt;if(dist<en.r+player.r+.25&&en.c<=0){en.c=.75;player.h-=SPEC.enemy.damage;burst(player.x,player.y,player.z,SPEC.visual.enemy,12)}}if(SPEC.template==='puzzle'&&(keys.has('e')||keys.has('interact'))){keys.delete('e');keys.delete('interact');var near=nodes.filter(function(n){return !n.active}).sort(function(a,b){return Math.hypot(a.x-player.x,a.z-player.z)-Math.hypot(b.x-player.x,b.z-player.z)})[0];if(near&&Math.hypot(near.x-player.x,near.z-player.z)<3){var expected=SPEC.puzzleSequence[progress];if(near.order===expected){near.active=true;progress++;score+=300;burst(near.x,near.y,near.z,SPEC.visual.accent,20)}else{nodes.forEach(function(n){n.active=false});progress=0;player.h-=8}}}if(SPEC.template==='arena')progress=defeated;else if(SPEC.template==='survival')progress=Math.min(SPEC.objective.target,Math.floor(elapsed));else if(SPEC.template==='collector')progress=collected}
for(i=0;i<items.length;i++){item=items[i];if(!item.dead&&Math.hypot(item.x-player.x,item.z-player.z)<item.r+player.r+.35&&Math.abs(item.y-player.y)<1.8){item.dead=true;collected++;score+=item.value||100;burst(item.x,item.y,item.z,SPEC.visual.collectible,14);if(SPEC.template==='collector')progress=collected}}
for(i=0;i<particles.length;i++){var pa=particles[i];pa.x+=pa.vx*dt;pa.y+=pa.vy*dt;pa.z+=pa.vz*dt;pa.vy-=7*dt;pa.l-=dt}particles=particles.filter(function(p){return p.l>0});if(player.h<=0){player.h=0;finish(false)}else if(progress>=SPEC.objective.target)finish(true);hud()}
function finish(win){if(!run)return;run=false;status=win?'victory':'defeat';var s=document.getElementById('start');s.innerHTML='<strong>'+(win?'MISSION COMPLETE':'RUN FAILED')+'</strong><span>'+(win?SPEC.narrative.victoryText:SPEC.narrative.defeatText)+' · Press R to retry</span>';s.classList.remove('hidden')}
function camera(){if(SPEC.template==='platformer')return{e:[player.x,player.y+5,zoom],t:[player.x+2,player.y+1,0]};if(SPEC.template==='runner')return{e:[player.x*.25,player.y+6,player.z-13],t:[player.x,player.y+1,player.z+10]};if(SPEC.perspective==='top-down')return{e:[player.x+Math.sin(yaw)*4,player.y+zoom*1.3,player.z+Math.cos(yaw)*4],t:[player.x,player.y,player.z]};var h=Math.cos(pitch)*zoom;return{e:[player.x-Math.sin(yaw)*h,player.y+4-Math.sin(pitch)*zoom,player.z-Math.cos(yaw)*h],t:[player.x,player.y+1,player.z]}}
function character(e,body,accent,ghost){var bob=Math.sin(performance.now()/170+e.id)*.04;cube(e.x,e.y+bob,e.z,.42,.65,.28,body,ghost?.25:0,e.a);cube(e.x,e.y+.92+bob,e.z,.32,.32,.32,accent,ghost?.45:.08);cube(e.x+.2,e.y-.8+bob,e.z,.15,.45,.16,body,0,e.a);cube(e.x-.2,e.y-.8+bob,e.z,.15,.45,.16,body,0,e.a)}
function render(t){var sky=rgb(SPEC.visual.sky),fog=rgb(SPEC.visual.fog),rect=canvas.getBoundingClientRect();gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(sky[0],sky[1],sky[2],1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);var cam=camera();gl.uniformMatrix4fv(U.P,false,persp(SPEC.renderer.fieldOfView*Math.PI/180,rect.width/Math.max(1,rect.height),.08,420));gl.uniformMatrix4fv(U.V,false,look(cam.e,cam.t));gl.uniform3f(U.E,cam.e[0],cam.e[1],cam.e[2]);gl.uniform3f(U.F,fog[0],fog[1],fog[2]);gl.uniform3f(U.L,-.45,-1,.25);gl.uniform1f(U.FN,SPEC.template==='runner'?25:28);gl.uniform1f(U.FF,SPEC.template==='runner'?105:SPEC.world.size*1.25);gl.uniform1f(U.T,t);
var half=SPEC.world.size/2;if(SPEC.template==='runner'){for(var seg=Math.floor(player.z/18)-2;seg<Math.floor(player.z/18)+9;seg++){cube(0,-.55,seg*18,7,.5,9,SPEC.visual.ground);cube(-7.3,.1,seg*18,.12,.05,9,SPEC.visual.accent,.4);cube(7.3,.1,seg*18,.12,.05,9,SPEC.visual.secondaryAccent,.4)}}else if(SPEC.template==='platformer'){for(var i=0;i<platforms.length;i++){var p=platforms[i];cube(p.x,p.y,p.z||0,p.w/2,p.h/2,3,SPEC.visual.ground,.08)}}else{cube(0,-.65,0,half,.6,half,SPEC.visual.ground);for(i=0;i<14;i++){var a=i/14*Math.PI*2;cube(Math.cos(a)*(half+3),1.5+random()*0,Math.sin(a)*(half+3),1.2,2.2,1.2,i%2?SPEC.visual.horizon:SPEC.visual.ground,.1)}}
for(i=0;i<obstacles.length;i++){var o=obstacles[i];if(SPEC.template==='runner'&&o.z<player.z-10)continue;cube(o.x,o.y,o.z,o.sx,o.sy,o.sz,o.hit?SPEC.visual.enemy:SPEC.visual.horizon,o.hit?.2:0)}for(i=0;i<items.length;i++){var it=items[i];if(!it.dead)cube(it.x,it.y+Math.sin(t*2+it.id)*.2,it.z,.32,.5,.32,SPEC.visual.collectible,.8,t)}for(i=0;i<nodes.length;i++){var n=nodes[i];cube(n.x,n.y,n.z,.65,1.2,.65,n.active?SPEC.visual.secondaryAccent:SPEC.visual.horizon,n.active?.8:.12,t*.2)}for(i=0;i<enemies.length;i++){var e=enemies[i];if(!e.dead)character(e,SPEC.visual.enemy,SPEC.visual.horizon,false)}for(i=0;i<shots.length;i++){var sh=shots[i];cube(sh.x,1.2,sh.z,.18,.18,.18,SPEC.visual.projectile,1)}character(player,SPEC.visual.player,SPEC.visual.accent,false);for(i=0;i<particles.length;i++){var pa=particles[i];cube(pa.x,pa.y,pa.z,.06,.06,.06,pa.c,.8)}}
function hud(){document.getElementById('score').textContent='Score '+score;document.getElementById('progress').textContent='Progress '+progress+'/'+SPEC.objective.target+' · '+fps+' FPS';document.getElementById('health').style.width=Math.max(0,player.h/player.max*100)+'%'}
function resize(){var rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,SPEC.quality==='ultra'?1.8:SPEC.quality==='high'?1.5:1.2);canvas.width=Math.max(640,Math.floor(rect.width*dpr));canvas.height=Math.max(360,Math.floor(rect.height*dpr))}
function loop(now){var dt=Math.min(.033,Math.max(0,(now-(last||now))/1000));last=now;if(run)update(dt,now/1000);frames++;if(now-fpsClock>500){fps=Math.round(frames/Math.max(.001,(now-fpsClock)/1000));frames=0;fpsClock=now}render(now/1000);requestAnimationFrame(loop)}
addEventListener('resize',resize);addEventListener('keydown',function(e){var k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(k==='r')reset();if(k==='enter'&&!run)reset()});addEventListener('keyup',function(e){keys.delete(e.key.toLowerCase())});canvas.addEventListener('pointerdown',function(e){if(!run){reset();return}drag=true;dragX=e.clientX;dragY=e.clientY;keys.add('attack');canvas.setPointerCapture(e.pointerId);canvas.focus()});canvas.addEventListener('pointermove',function(e){if(!drag)return;yaw-=(e.clientX-dragX)*.006;pitch=clamp(pitch-(e.clientY-dragY)*.004,-.82,.22);dragX=e.clientX;dragY=e.clientY});canvas.addEventListener('pointerup',function(e){drag=false;keys.delete('attack');canvas.releasePointerCapture(e.pointerId)});canvas.addEventListener('wheel',function(e){e.preventDefault();zoom=clamp(zoom+e.deltaY*.012,8,30)},{passive:false});document.getElementById('start').onclick=reset;document.querySelectorAll('[data-key]').forEach(function(b){function down(e){e.preventDefault();keys.add(b.dataset.key);if(!run)reset()}function up(e){e.preventDefault();keys.delete(b.dataset.key)}b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up)});resize();reset();run=false;document.getElementById('start').classList.remove('hidden');requestAnimationFrame(loop);
})();
</script>
</body>
</html>`;
}


function buildFlightStandaloneHtml(spec: GameBuildSpec) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" />
<title>${escapeHtml(spec.title)} — Gameforge Open-World Flight</title>
<style>
*{box-sizing:border-box}html,body{margin:0;height:100%;overflow:hidden;background:#06111a;color:#fff;font-family:Inter,system-ui,Arial,sans-serif}canvas{display:block;width:100%;height:100%;outline:none;cursor:grab;touch-action:none}.hud{position:fixed;inset:0;pointer-events:none}.top{display:flex;justify-content:space-between;gap:12px;padding:14px}.panel{background:rgba(4,12,20,.7);border:1px solid rgba(255,255,255,.16);backdrop-filter:blur(15px);border-radius:16px;padding:11px 13px;box-shadow:0 16px 44px rgba(0,0,0,.28)}h1{font-size:16px;margin:0}.small{font-size:11px;color:#d6e6ee;margin-top:5px;max-width:460px;line-height:1.45}.meters{display:grid;grid-template-columns:repeat(4,minmax(72px,1fr));gap:7px;margin-top:8px}.metric{background:rgba(0,0,0,.25);border:1px solid rgba(255,255,255,.1);border-radius:11px;padding:7px 9px}.metric b{display:block;font-size:14px}.metric span{font-size:9px;color:#b7cbd5;text-transform:uppercase;letter-spacing:.12em}.bar{height:6px;background:rgba(255,255,255,.12);border-radius:999px;overflow:hidden;margin-top:8px}.bar i{display:block;height:100%;width:100%;background:linear-gradient(90deg,${spec.visual.secondaryAccent},${spec.visual.collectible});transition:width .12s}.center{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);text-align:center;background:rgba(3,10,18,.8);border:1px solid rgba(255,255,255,.17);padding:28px 32px;border-radius:24px;pointer-events:auto;cursor:pointer;box-shadow:0 30px 90px rgba(0,0,0,.48)}.center.hidden{display:none}.center strong{font-size:clamp(24px,4vw,39px);display:block}.center span{font-size:13px;color:#dbe9f0;display:block;margin-top:10px;line-height:1.65;max-width:620px}.mission{position:absolute;left:14px;bottom:14px;max-width:420px}.message{position:absolute;left:50%;bottom:13%;transform:translateX(-50%);max-width:min(740px,86vw);text-align:center;font-weight:800;text-shadow:0 2px 12px #000}.reticle{position:absolute;left:50%;top:50%;width:22px;height:22px;border:1px solid rgba(255,255,255,.45);border-radius:50%;transform:translate(-50%,-50%)}.reticle:after{content:"";position:absolute;left:50%;top:50%;width:4px;height:4px;border-radius:50%;background:#fff;transform:translate(-50%,-50%)}.error{display:none;position:fixed;inset:0;z-index:10;place-items:center;background:#050b10;padding:30px;text-align:center}.error.show{display:grid}.mobile{display:none;position:absolute;inset:auto 12px 12px;justify-content:space-between;pointer-events:auto}.pad,.actions{display:grid;gap:7px}.pad{grid-template-columns:repeat(3,46px)}.actions{grid-template-columns:repeat(2,54px);align-content:end}.touch{height:46px;border:1px solid rgba(255,255,255,.18);border-radius:14px;background:rgba(0,0,0,.52);color:#fff;font-weight:900}.blank{visibility:hidden}@media(max-width:700px){.meters{grid-template-columns:repeat(2,minmax(70px,1fr))}.mission{display:none}}@media(pointer:coarse){.mobile{display:flex}.reticle{display:none}}
</style>
</head>
<body>
<canvas id="game" tabindex="0" aria-label="${escapeHtml(spec.title)} open-world bird simulator"></canvas>
<div class="hud">
  <div class="top">
    <div class="panel"><h1>${escapeHtml(spec.title)}</h1><div class="small">${escapeHtml(spec.objective.description)}</div></div>
    <div class="panel"><div class="meters"><div class="metric"><span>Altitude</span><b id="alt">0 m</b></div><div class="metric"><span>Speed</span><b id="spd">0 km/h</b></div><div class="metric"><span>Wind</span><b id="wind">0</b></div><div class="metric"><span>Landmarks</span><b id="prog">0/${spec.objective.target}</b></div></div><div class="bar"><i id="stamina"></i></div></div>
  </div>
  <div class="reticle"></div>
  <div class="message" id="message">${escapeHtml(spec.narrative.openingLine)}</div>
  <div class="center" id="start"><strong>Enter the Open Sky</strong><span>W/S pitch · A/D bank and turn · drag mouse to steer · Space flap · Shift dive/accelerate · Ctrl brake and land · R restart</span></div>
  <div class="mission panel"><b>Free-flight objective</b><div class="small">Explore the world, fly through luminous aerial landmarks, ride thermal currents and land anywhere safely. The world remains open after completion.</div></div>
  <div class="mobile"><div class="pad"><button class="touch blank"></button><button class="touch" data-key="w">▲</button><button class="touch blank"></button><button class="touch" data-key="a">◀</button><button class="touch" data-key="s">▼</button><button class="touch" data-key="d">▶</button></div><div class="actions"><button class="touch" data-key="control">BRAKE</button><button class="touch" data-key=" ">FLAP</button><button class="touch" data-key="shift">DIVE</button></div></div>
</div>
<div class="error" id="error"><div class="panel"><h2>WebGL 2 is required</h2><p>Enable hardware acceleration or open this game in a current Chrome, Edge, Firefox or Safari browser.</p></div></div>
<script>
(function(){'use strict';
var SPEC=${safeJson(spec)},F=SPEC.flight||{cruiseSpeed:20,maxSpeed:44,flapLift:8.5,glideEfficiency:.86,turnRate:1.65,windStrength:5.5,thermalCount:7};
var canvas=document.getElementById('game'),gl=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});if(!gl){document.getElementById('error').classList.add('show');return}
var VS='#version 300 es\\nprecision highp float;layout(location=0)in vec3 p;layout(location=1)in vec3 n;uniform mat4 P,V,M;out vec3 N,W;void main(){vec4 w=M*vec4(p,1.);W=w.xyz;N=mat3(M)*n;gl_Position=P*V*w;}';
var FS='#version 300 es\\nprecision highp float;in vec3 N,W;uniform vec3 C,FC,L;uniform float E,FN,FF;out vec4 o;void main(){float d=max(.18,dot(normalize(N),normalize(-L)));vec3 c=C*(.48+d*.62)+E*C;float fog=smoothstep(FN,FF,length(W));o=vec4(mix(c,FC,fog*.82),1.);}';
function shader(t,s){var x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x)||'shader');return x}var pr=gl.createProgram();gl.attachShader(pr,shader(gl.VERTEX_SHADER,VS));gl.attachShader(pr,shader(gl.FRAGMENT_SHADER,FS));gl.linkProgram(pr);gl.useProgram(pr);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);var U={P:gl.getUniformLocation(pr,'P'),V:gl.getUniformLocation(pr,'V'),M:gl.getUniformLocation(pr,'M'),C:gl.getUniformLocation(pr,'C'),FC:gl.getUniformLocation(pr,'FC'),L:gl.getUniformLocation(pr,'L'),E:gl.getUniformLocation(pr,'E'),FN:gl.getUniformLocation(pr,'FN'),FF:gl.getUniformLocation(pr,'FF')};
var verts=[-1,-1,1,0,0,1,1,-1,1,0,0,1,1,1,1,0,0,1,-1,-1,1,0,0,1,1,1,1,0,0,1,-1,1,1,0,0,1,1,-1,-1,0,0,-1,-1,-1,-1,0,0,-1,-1,1,-1,0,0,-1,1,-1,-1,0,0,-1,-1,1,-1,0,0,-1,1,1,-1,0,0,-1,-1,-1,-1,-1,0,0,-1,-1,1,-1,0,0,-1,1,1,-1,0,0,-1,-1,-1,-1,0,0,-1,1,1,-1,0,0,-1,1,-1,-1,0,0,1,-1,1,1,0,0,1,-1,-1,1,0,0,1,1,-1,1,0,0,1,-1,1,1,0,0,1,1,-1,1,0,0,1,1,1,1,0,0,1,-1,1,-1,0,1,0,-1,1,1,0,1,0,1,1,1,0,1,0,-1,1,-1,0,1,0,1,1,1,0,1,0,1,1,-1,0,1,0,-1,-1,1,0,-1,0,-1,-1,-1,0,-1,0,1,-1,-1,0,-1,0,-1,-1,1,0,-1,0,1,-1,-1,0,-1,0,1,-1,1,0,-1,0];var va=gl.createVertexArray(),vb=gl.createBuffer();gl.bindVertexArray(va);gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,24,12);
function I(){return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}function mul(a,b){var o=new Array(16);for(var r=0;r<4;r++)for(var c=0;c<4;c++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}function tr(x,y,z){var m=I();m[12]=x;m[13]=y;m[14]=z;return m}function sc(x,y,z){var m=I();m[0]=x;m[5]=y;m[10]=z;return m}function ry(a){var m=I(),c=Math.cos(a),s=Math.sin(a);m[0]=c;m[2]=-s;m[8]=s;m[10]=c;return m}function rz(a){var m=I(),c=Math.cos(a),s=Math.sin(a);m[0]=c;m[1]=s;m[4]=-s;m[5]=c;return m}function rx(a){var m=I(),c=Math.cos(a),s=Math.sin(a);m[5]=c;m[6]=s;m[9]=-s;m[10]=c;return m}function persp(f,a,n,z){var t=1/Math.tan(f/2),m=new Array(16).fill(0);m[0]=t/a;m[5]=t;m[10]=(z+n)/(n-z);m[11]=-1;m[14]=2*z*n/(n-z);return m}function look(e,t){var zx=e[0]-t[0],zy=e[1]-t[1],zz=e[2]-t[2],zl=Math.hypot(zx,zy,zz)||1;zx/=zl;zy/=zl;zz/=zl;var xx=-zz,xz=zx,xl=Math.hypot(xx,xz)||1;xx/=xl;xz/=xl;var yx=zy*xz,yz=-zy*xx,yy=zz*xx-zx*xz;return[xx,yx,zx,0,0,yy,zy,0,xz,yz,zz,0,-xx*e[0]-xz*e[2],-yx*e[0]-yy*e[1]-yz*e[2],-zx*e[0]-zy*e[1]-zz*e[2],1]}
function col(h){h=(h||'#ffffff').replace('#','');return[parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255]}function cube(x,y,z,sx,sy,sz,c,e,yaw,pitch,roll){var m=mul(tr(x,y,z),mul(ry(yaw||0),mul(rx(pitch||0),mul(rz(roll||0),sc(sx,sy,sz)))));gl.uniformMatrix4fv(U.M,false,m);var q=col(c);gl.uniform3f(U.C,q[0],q[1],q[2]);gl.uniform1f(U.E,e||0);gl.drawArrays(gl.TRIANGLES,0,36)}
var seed=0;for(var si=0;si<SPEC.title.length;si++)seed=(seed*31+SPEC.title.charCodeAt(si))>>>0;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}function terrain(x,z){var ridge=Math.sin(x*.035+seed*.00001)*7+Math.cos(z*.03-seed*.00002)*6;var peaks=Math.pow(Math.max(0,Math.sin((x+z)*.018)+Math.cos((x-z)*.021)),2)*7;var detail=Math.sin(x*.11)*Math.cos(z*.09)*1.7;var river=Math.exp(-Math.pow((x*.18+Math.sin(z*.025)*8)/10,2))*9;return Math.max(-2,ridge+peaks+detail-river)}
var size=SPEC.world.size||240,half=size/2,keys=new Set(),run=false,last=0,elapsed=0,yaw=0,pitch=.04,roll=0,speed=F.cruiseSpeed,vy=0,stamina=100,windX=0,windZ=0,wing=0,progress=0,score=0,drag=false,dx=0,dy=0,messageUntil=5;var bird={x:0,y:28,z:-half*.18};var landmarks=[],thermals=[],trees=[],clouds=[];for(var i=0;i<SPEC.objective.target;i++){var a=i/SPEC.objective.target*Math.PI*2+rand()*.5,r=35+rand()*(half-45);landmarks.push({x:Math.cos(a)*r,z:Math.sin(a)*r,y:14+rand()*40,got:false,phase:rand()*6.28})}for(i=0;i<F.thermalCount;i++){a=i/F.thermalCount*Math.PI*2+rand();r=25+rand()*(half-35);thermals.push({x:Math.cos(a)*r,z:Math.sin(a)*r,r:7+rand()*5})}for(i=0;i<100;i++){var tx=(rand()-.5)*size,tz=(rand()-.5)*size,th=terrain(tx,tz);if(th>0)trees.push({x:tx,z:tz,y:th,s:.6+rand()*1.1})}for(i=0;i<24;i++)clouds.push({x:(rand()-.5)*size*1.5,z:(rand()-.5)*size*1.5,y:42+rand()*45,s:3+rand()*5});
function reset(){bird.x=0;bird.z=-half*.18;bird.y=terrain(bird.x,bird.z)+25;yaw=0;pitch=.05;roll=0;speed=F.cruiseSpeed;vy=0;stamina=100;progress=0;score=0;elapsed=0;landmarks.forEach(function(n){n.got=false});run=true;document.getElementById('start').classList.add('hidden');canvas.focus();messageUntil=4;document.getElementById('message').textContent=SPEC.narrative.openingLine}
function update(dt,t){elapsed+=dt;var turn=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),pitchInput=(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0);yaw-=turn*F.turnRate*dt;pitch=Math.max(-.62,Math.min(.62,pitch+pitchInput*dt*1.05));roll+=(turn*.62-roll)*Math.min(1,dt*4);var dive=keys.has('shift'),brake=keys.has('control')||keys.has('ctrl'),target=brake?Math.max(7,F.cruiseSpeed*.45):dive?F.maxSpeed:F.cruiseSpeed+Math.max(0,-pitch)*8;if(dive)pitch=Math.max(-.62,pitch-dt*.18);speed+=(target-speed)*Math.min(1,dt*(dive?2.8:1.35));if(keys.has(' ')&&stamina>2){stamina=Math.max(0,stamina-18*dt);vy+=F.flapLift*dt*2.8;speed=Math.min(F.maxSpeed,speed+7*dt);wing+=dt*20}else{stamina=Math.min(100,stamina+10*dt);wing+=dt*(4+speed*.12)}windX=Math.sin(t*.17+seed*.01)*F.windStrength;windZ=Math.cos(t*.13-seed*.005)*F.windStrength*.62;var cp=Math.cos(pitch),fx=Math.sin(yaw)*cp,fy=Math.sin(pitch),fz=Math.cos(yaw)*cp,sink=(1-F.glideEfficiency)*5.5+Math.max(0,F.cruiseSpeed-speed)*.045;vy+=(fy*speed*.24-sink)*dt;vy*=Math.pow(.94,dt*60);bird.x+=(fx*speed+windX*.32)*dt;bird.z+=(fz*speed+windZ*.32)*dt;bird.y+=(fy*speed*.62+vy)*dt;if(bird.x>half)bird.x=-half;if(bird.x<-half)bird.x=half;if(bird.z>half)bird.z=-half;if(bird.z<-half)bird.z=half;for(var q=0;q<thermals.length;q++){var th=thermals[q],dd=Math.hypot(bird.x-th.x,bird.z-th.z);if(dd<th.r)vy+=(1-dd/th.r)*12*dt}var ground=terrain(bird.x,bird.z)+1.4;if(bird.y<ground){bird.y=ground;vy=0;speed=Math.max(5,speed*.58);pitch=Math.max(-.05,pitch)}for(q=0;q<landmarks.length;q++){var lm=landmarks[q];if(!lm.got&&Math.hypot(bird.x-lm.x,bird.y-lm.y,bird.z-lm.z)<4.3){lm.got=true;progress++;score+=500;messageUntil=t+2.5;document.getElementById('message').textContent=progress>=SPEC.objective.target?SPEC.narrative.victoryText:'Aerial landmark discovered · '+progress+'/'+SPEC.objective.target}}if(t>messageUntil)document.getElementById('message').textContent=progress>=SPEC.objective.target?'Free flight unlocked — keep exploring the world.':'';document.getElementById('alt').textContent=Math.max(0,Math.round(bird.y-terrain(bird.x,bird.z)))+' m';document.getElementById('spd').textContent=Math.round(speed*3.6)+' km/h';document.getElementById('wind').textContent=Math.round(Math.hypot(windX,windZ))+' m/s';document.getElementById('prog').textContent=progress+'/'+SPEC.objective.target;document.getElementById('stamina').style.width=stamina+'%'}
function drawBird(t){var flap=Math.sin(wing)*.55,body=SPEC.visual.player,accent=SPEC.visual.accent;cube(bird.x,bird.y,bird.z,.5,.32,1.15,body,.03,yaw,pitch,roll);var fx=Math.sin(yaw)*Math.cos(pitch),fz=Math.cos(yaw)*Math.cos(pitch);cube(bird.x+fx*.8,bird.y+.12,bird.z+fz*.8,.28,.25,.35,accent,.06,yaw,pitch,roll);cube(bird.x+fx*1.18,bird.y+.05,bird.z+fz*1.18,.12,.08,.24,SPEC.visual.collectible,.12,yaw,pitch,roll);cube(bird.x,bird.y,bird.z,.22,.08,1.75,body,.02,yaw+Math.PI/2,pitch+flap,roll);cube(bird.x,bird.y,bird.z,.22,.08,1.75,body,.02,yaw-Math.PI/2,pitch-flap,roll);cube(bird.x-fx*.95,bird.y-.05,bird.z-fz*.95,.62,.06,.5,accent,.02,yaw,pitch,roll)}
function render(t){var rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,SPEC.quality==='ultra'?1.7:1.4),w=Math.max(640,Math.floor(rect.width*dpr)),h=Math.max(360,Math.floor(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);var sky=col(SPEC.visual.sky),fog=col(SPEC.visual.fog);gl.clearColor(sky[0],sky[1],sky[2],1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);var cp=Math.cos(pitch),fx=Math.sin(yaw)*cp,fy=Math.sin(pitch),fz=Math.cos(yaw)*cp,eye=[bird.x-fx*17,bird.y+5-fy*5,bird.z-fz*17],target=[bird.x+fx*11,bird.y+fy*7,bird.z+fz*11];gl.uniformMatrix4fv(U.P,false,persp((SPEC.renderer.fieldOfView||74)*Math.PI/180,w/h,.1,700));gl.uniformMatrix4fv(U.V,false,look(eye,target));gl.uniform3f(U.FC,fog[0],fog[1],fog[2]);gl.uniform3f(U.L,-.45,-1,.25);gl.uniform1f(U.FN,75);gl.uniform1f(U.FF,size*.95);gl.bindVertexArray(va);
/* ocean and procedural terrain */cube(0,-4,0,half*1.1,.5,half*1.1,'#2b82a8',.08);var step=size/28;for(var gx=-14;gx<14;gx++)for(var gz=-14;gz<14;gz++){var x=(gx+.5)*step,z=(gz+.5)*step,y=terrain(x,z);var c=y>15?'#d9e6e8':y>7?'#65795f':y>0?'#3f7452':'#b9a06b';cube(x,y/2-3,z,step*.51,Math.max(.5,(y+6)/2),step*.51,c,.02)}
/* sun, clouds, forest, thermals and landmarks */cube(-70,80,-100,6,6,6,'#ffe79a',1);for(var i=0;i<clouds.length;i++){var cl=clouds[i],cx=cl.x+(t*1.8+i)%size-size/2;cube(cx,cl.y,cl.z,cl.s,1.2,cl.s*.65,'#f4fbff',.06)}for(i=0;i<trees.length;i++){var trr=trees[i];cube(trr.x,trr.y+trr.s*1.2,trr.z,.22*trr.s,1.2*trr.s,.22*trr.s,'#68492f',0);cube(trr.x,trr.y+trr.s*2.7,trr.z,.9*trr.s,1.5*trr.s,.9*trr.s,'#286345',.02)}for(i=0;i<thermals.length;i++){var th=thermals[i];for(var k=0;k<5;k++)cube(th.x,8+k*8,th.z,.18+k*.05,3.2,.18+k*.05,SPEC.visual.secondaryAccent,.45,t*.5+k)}for(i=0;i<landmarks.length;i++){var lm=landmarks[i];if(!lm.got){var pulse=1+Math.sin(t*2+lm.phase)*.18;cube(lm.x,lm.y,lm.z,1.7*pulse,.12,1.7*pulse,SPEC.visual.collectible,.9,t);cube(lm.x,lm.y,lm.z,.12,1.7*pulse,1.7*pulse,SPEC.visual.secondaryAccent,.8,t)}}drawBird(t)}
function loop(now){var dt=Math.min(.033,Math.max(0,(now-(last||now))/1000));last=now;if(run)update(dt,now/1000);render(now/1000);requestAnimationFrame(loop)}
addEventListener('keydown',function(e){var k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(k==='r')reset();if(k==='enter'&&!run)reset()});addEventListener('keyup',function(e){keys.delete(e.key.toLowerCase())});canvas.addEventListener('pointerdown',function(e){if(!run){reset();return}drag=true;dx=e.clientX;dy=e.clientY;canvas.setPointerCapture(e.pointerId);canvas.focus()});canvas.addEventListener('pointermove',function(e){if(!drag)return;yaw-=(e.clientX-dx)*.0045;pitch=Math.max(-.62,Math.min(.62,pitch-(e.clientY-dy)*.0035));dx=e.clientX;dy=e.clientY});canvas.addEventListener('pointerup',function(e){drag=false;canvas.releasePointerCapture(e.pointerId)});document.getElementById('start').addEventListener('click',reset);document.querySelectorAll('[data-key]').forEach(function(b){function down(e){e.preventDefault();keys.add(b.dataset.key);if(!run)reset()}function up(e){e.preventDefault();keys.delete(b.dataset.key)}b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up)});requestAnimationFrame(loop);
})();
</script>
</body>
</html>`;
}

function escapeHtml(value: string) {
  return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] || character);
}
